Add text content to banner.html sample page
Office-of-Digital-Services/California-State-Web-Template-Website pull request #1221
Opened 2023-02-08 21:23 UTC by jon-grant-state-ca-gov

Add 'a(n):' to description in banner sample page

2023-02-10 00:53 UTC, kkoryaka requested changes
Change it to a(an)

2023-02-10 17:59 UTC, jon-grant-state-ca-gov commented
@kkoryaka Ok, that text has been changed

2023-02-10 23:01 UTC, carterm approved these changes
changed to a(an)

2023-02-11 01:28 UTC, kkoryaka approved these changes

2023-02-13 21:31 UTC, merged